@extends('master')
@section('content')
    @auth
        @can('admin')
            @include('admin.dashboard')
        @else
            @include('layouts.navigasi.navbar')
            @include('layouts.hero')
            @include('layouts.best')
            @include('layouts.ourproduct')
            @include('layouts.footer')
        @endcan
        @include('script')
    @endauth
    @guest
        @include('layouts.navigasi.navbarguest')
        @include('layouts.hero')
        @include('layouts.best')
        @include('layouts.ourproduct')
        @include('layouts.footerguest')
        @include('script')
    @endguest
@endsection
